RocksDB updates
nanocurrency/nano-docs pull request #425
Opened 2020-10-23 16:49 UTC by wezrule

Solves https://github.com/nanocurrency/nano-docs/issues/360

2020-10-26 20:36 UTC, zhyatt requested changes

2020-10-26 20:36 UTC, zhyatt commented on docs/running-a-node/ledger-management.md
> +* Cannot execute CLI commands which require writing to the database while a node is running, such as `nano_node --peer_clear, these must be executed when the node is stopped
Missing back tick after peer_clear here

2020-10-27 00:35 UTC, wezrule commented on docs/running-a-node/ledger-management.md
> +* Cannot execute CLI commands which require writing to the database while a node is running, such as `nano_node --peer_clear, these must be executed when the node is stopped
Added thanks!

2020-10-27 19:58 UTC, zhyatt approved these changes

2021-01-08 17:25 UTC, zhyatt approved these changes

2021-03-15 18:04 UTC, zhyatt commented on docs/running-a-node/ledger-management.md
> +An existing LMDB ledger can be upgraded by running the [--migrate_database_lmdb_to_rocksdb](/commands/command-line-interface/#-migrate_database_lmdb_to_rocksdb) CLI command. This process can take som
- [ ] Add more emphasis on the requirement to manually enable RocksDB after migration - might not be obvious that extra step is needed

2021-05-14 14:16 UTC, zhyatt approved these changes

2021-05-14 14:16 UTC, merged