docker: use IPv4 in docker-compose config
nanocurrency/nano-docs pull request #460
Opened 2021-02-01 21:25 UTC by angristan

The bracket notation for IPv6 doesn't seem to be supported: https://github.com/docker/compose/issues/7001.

Without the brackets, I didn't manage to reach the RPC service with IPv6. Works fine with `127.0.0.1` though.

2021-02-02 04:02 UTC, argakiig requested changes
It may be important to note that Docker Compose Schema 2.1 and prior all support the ipv6 bracket notation, But if you are using a current schema(3.7) you will need to use the ipv4 address instead. It may be better to call out the differences in schema, although per the specifications version is no longer settable. Perhaps call out both depending on the Docker-Compose schema being used?

2021-02-03 12:53 UTC, angristan commented
> It may be important to note that Docker Compose Schema 2.1 and prior all support the ipv6 bracket notation

The example in the docs uses `version: '3'`. Since we don't seem to be using features specific to version 3, it would be fine to use an older version I guess. However, I tried with version 2.1 and I have the same errors with the bracket notation:

```
root@nano:~/lol# head docker-compose.yml
version: '2.1'
services:
  node:
    image: "nanocurrency/nano:V21.2"
    restart: "unless-stopped"
    ports:
     - "[::1]:7076:7076"
     - "[::1]:7078:7078"
root@nano:~/lol# docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.node.ports contains an invalid type, it should be a number, or an object
services.node.ports contains an invalid type, it should be a number, or an object
```
```
root@nano:~/lol# head docker-compose.yml
version: '3'
services:
  node:
    image: "nanocurrency/nano:V21.2"
    restart: "unless-stopped"
    ports:
     - "[::1]:7076:7076"
     - "[::1]:7078:7078"
root@nano:~/lol# docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.node.ports contains an invalid type, it should be a number, or an object
services.node.ports contains an invalid type, it should be a number, or an object
```

😕

2021-02-07 06:16 UTC, argakiig commented
> > It may be important to note that Docker Compose Schema 2.1 and prior all support the ipv6 bracket notation
> 
> The example in the docs uses `version: '3'`. Since we don't seem to be using features specific to version 3, it would be fine to use an older version I guess. However, I tried with version 2.1 and I have the same errors with the bracket notation:
> 
> ```
> root@nano:~/lol# head docker-compose.yml
> version: '2.1'
> services:
>   node:
>     image: "nanocurrency/nano:V21.2"
>     restart: "unless-stopped"
>     ports:
>      - "[::1]:7076:7076"
>      - "[::1]:7078:7078"
> root@nano:~/lol# docker-compose up
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.node.ports contains an invalid type, it should be a number, or an object
> services.node.ports contains an invalid type, it should be a number, or an object
> ```
> 
> ```
> root@nano:~/lol# head docker-compose.yml
> version: '3'
> services:
>   node:
>     image: "nanocurrency/nano:V21.2"
>     restart: "unless-stopped"
>     ports:
>      - "[::1]:7076:7076"
>      - "[::1]:7078:7078"
> root@nano:~/lol# docker-compose up
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.node.ports contains an invalid type, it should be a number, or an object
> services.node.ports contains an invalid type, it should be a number, or an object
> ```
> 
> 😕

The reason it doesn't work on newer daemons is they also deprecated the version tag, so it's useless with newer docker-compose installs which is likely why it doesn't work for you. I can look up the version that this happened

2021-02-07 06:17 UTC, argakiig approved these changes

2021-02-08 18:36 UTC, merged