Add balance-lru-prio.svg to spam-work-and-prioritization.md
nanocurrency/nano-docs pull request #664
Opened 2023-03-19 15:22 UTC by qwahzi

Add balance-lru-prio.svg to spam-work-and-prioritization.md
Also remove unnecessary "bucket" descriptor from bucket table

2023-05-24 19:57 UTC, thsfs commented on docs/images/whitepaper/balance-lru-prio.svg
When visualizing the image in SVG format in Firefox/Ubuntu there are some parts of the image that overlap. Opening in Google Chrome it doesn't happen. 

Screenshot:
![image](https://github.com/nanocurrency/nano-docs/assets/82097354/a88bc7f5-a5af-4ac8-8c74-3a7e3634f59a)

2023-05-24 20:00 UTC, thsfs requested changes
When visualizing the image in SVG format in Firefox/Ubuntu there are some parts of the image that overlap. Opening it in Google Chrome the problem doesn't happen.

![image](https://github.com/nanocurrency/nano-docs/assets/82097354/9f3db0e8-e697-4778-9900-fac7ee52e4d4)

2023-05-26 22:42 UTC, qwahzi commented
> When visualizing the image in SVG format in Firefox/Ubuntu there are some parts of the image that overlap. Opening it in Google Chrome the problem doesn't happen.
> 
> ![image](https://user-images.githubusercontent.com/82097354/240728276-9f3db0e8-e697-4778-9900-fac7ee52e4d4.png)

I couldn't figure out how to get the svg to work, so I replaced it with a png for now

2023-05-27 19:31 UTC, thsfs approved these changes

2023-05-27 19:42 UTC, merged